"""empty message

Revision ID: 84eae6271fdd
Revises: fd09cadd06ff
Create Date: 2022-03-30 13:05:36.989916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84eae6271fdd'
down_revision = 'fd09cadd06ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.Column('sem', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_table('trig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notify_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notify_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('trig')
    op.drop_table('subject')
    # ### end Alembic commands ###
