"""empty message

Revision ID: f36318a2cf43
Revises: 84eae6271fdd
Create Date: 2022-03-30 13:22:33.998869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36318a2cf43'
down_revision = '84eae6271fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'post_id')
    # ### end Alembic commands ###
