"""added module

Revision ID: fd09cadd06ff
Revises: 0fd013ce0afc
Create Date: 2022-01-14 21:37:44.490473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd09cadd06ff'
down_revision = '0fd013ce0afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('module', sa.String(length=50), nullable=False))
    op.alter_column('notes', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('notes', 'module')
    # ### end Alembic commands ###
